services:
  api:
    build: .
    container_name: api
    ports:
      - "8001:3636"
    volumes:
      - .:/app
    command: ['npm', "run", "dev"]
    restart: unless-stopped
  mysql:
    image: mysql:9.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3308"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
